[project]
name = "mcp-tcsai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "langchain-mistralai>=0.2.12",
    "mcp-use>=1.3.10",
]
